[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
lib_deps =
    knolleary/PubSubClient@^2.8
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/RTClib@^2.1.4
    https://github.com/chrisjoyce911/esp32FOTA.git
