[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
; 0=none 1=error 2=warn 3=info 4=debug 5=verbose — set to 1 for production
build_flags = -DCORE_DEBUG_LEVEL=1
lib_deps =
    knolleary/PubSubClient@^2.8
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/RTClib@^2.1.4
    https://github.com/chrisjoyce911/esp32FOTA.git
